### ISSUE TITLE
[Feature Request]:  adding logo to the google drive

### ISSUE THREAD

**Issue by jayanththalla** [apu52/METAVERSE#1032]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

In the google drive there is no logo in the navbar and the main page

### Use Case

I want to add the logo in the google drive

### Add ScreenShots

![image](https://github.com/user-attachments/assets/b45915d9-f408-431e-9dbe-e1892601f373)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a SSOC'24 contributor
- [X] I have starred the repository

**Comment by apu52** [comment]
@jayanththalla I have recently seen that u are contributing really consistently in this repo & all of the changes u have made are really great also .But just want to remind you that one contributor can only get 150 points max from a particular repo under GSSOC , so keep this rule in mind please , otherwise really want to see more of your amazing contributions.

**Comment by Subashree-selvaraj** [comment]
can you assign this issue to me?

**Comment by apu52** [comment]
> can you assign this issue to me?

i have already assigned u some issue previously , Please try to complete the previously assigned issue, Then ping me here , i will assign u then

**Comment by ayesha-firdaus** [comment]
Sir i would like to take up this issue

**Comment by apu52** [comment]
@ayesha-firdaus u are assigned
