### ISSUE TITLE
[Feature Request]: Add icon and change title

### ISSUE THREAD

**Issue by chaanakyaaM** [apu52/METAVERSE#1035]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I would like to add a appropriate icon and title to the hackathon website.

### Use Case

This improves the overall UI.

### Add ScreenShots

![image](https://github.com/user-attachments/assets/116a9dd0-550c-4748-b97d-51d16c451065)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a SSOC'24 contributor
- [X] I have starred the repository

**Comment by apu52** [comment]
@chaanakyaaM I have recently seen that u are contributing really consistently in this repo & all of the changes u have made are really great also .But just want to remind you that one contributor can only get 150 points max from a particular repo under GSSOC , so keep this rule in mind please , otherwise really want to see more of your amazing contributions.
