### ISSUE TITLE
Issue Regarding UI of AI- image generator

### ISSUE THREAD

**Issue by omsherikar** [apu52/METAVERSE#1250]
The UI of AI image generator is not up to the mark so I want to contribute to it please assign me this work

**Comment by apu52** [comment]
@omsherikar there are problem issue templates already present in the repo  please use them to raise your issue proper by filling up all the details . otherwise I can't be able to assign u the issue without proper clarification of your issue . So sorry to close this issue for now . But will be waiting for your new & proper issue
