### ISSUE TITLE
alignment of navbar and making it responsive

### ISSUE THREAD

**Issue by akanchha-rani** [apu52/METAVERSE#1270]
<img width="657" alt="Screenshot 2024-10-12 at 11 54 29 PM" src="https://github.com/user-attachments/assets/e47084b4-6f13-49cb-8d5e-9464d5305755">

i want to update your project navbar and make it responsive.

###  **Please assign this issue to me under gssoc '24 and the level of work i will do.**

**Comment by apu52** [comment]
@akanchha-rani there are  issue templates already present in the repo please use them to raise your issue proper by filling up all the details . otherwise I can't be able to assign u the issue without proper clarification of your issue . So sorry to close this issue for now . But will be waiting for your new & proper issue
