### ISSUE TITLE
Fix spelling of "HACKTOBERFEST" throughout README

### ISSUE THREAD

**Issue by Jaytailor15** [apu52/METAVERSE#1297]
Correct the spelling of "HACKTOBERFEST" to ensure consistency and clarity in the README file. This change enhances the professionalism of the project documentation.  

@sanjay-kv 
@apu52

**Comment by apu52** [comment]
@Jaytailor15 Please try to follow the issue templates which are already provided in the repo to raise your issue , otherwise it will be difficult for me/mentors to assign u the issue without much info.
This issue is good just try to raise a new issue on same topic using the issue templates already given 
Sorry to close this issue for now .
