### ISSUE TITLE
Backend  code architecture modification 

### ISSUE THREAD

**Issue by Amnyadav** [apu52/METAVERSE#1314]
As i see whole code of backend is in single server.js file which is not a good choice.
Because of these we faced many problems during adding any new feature and also scalibility issues are there.

I can structure whole code in readable and scalable code.

@apu52 assign me this

**Comment by apu52** [comment]
@Amnyadav Please try to follow the issue templates which are already provided in the repo to raise your issue , otherwise it will be difficult for me/mentors to assign u the issue without much info.
This issue is good just try to raise a new issue on same topic using the issue templates already given 
Sorry to close this issue for now
