### ISSUE TITLE
ADD Chat bot to the website 

### ISSUE THREAD

**Issue by shubhagarwal1** [apu52/METAVERSE#1319]
ref.
<img width="1433" alt="Screenshot 2024-10-25 at 5 13 21 AM" src="https://github.com/user-attachments/assets/240c72b3-eb50-4c1f-a59f-3b0e05795647">

**Comment by apu52** [comment]
@shubhagarwal1 Please try to follow the issue templates which are already provided in the repo to raise your issue , otherwise it will be difficult for me/mentors to assign u the issue without much info.
This issue is good just try to raise a new issue on same topic using the issue templates already given 
Sorry to close this issue for now .
