### ISSUE TITLE
Implement Skeleton Loading for the Landing Page 

### ISSUE THREAD

**Issue by shubhagarwal1** [apu52/METAVERSE#1347]
Skeleton loading is a UI pattern that provides a placeholder for content while it loads, enhancing the user experience by indicating that data is being fetched. For the landing page, you can implement skeleton loading by displaying greyed-out blocks or lines that mimic the layout of the actual content (like images, text, and buttons). This approach reduces perceived loading time, keeps users engaged, and prevents confusion about the page's state. Ensure the skeleton elements align with the final design to create a seamless transition once the content is fully loaded.
Hey @apu52 please assign me this issue.

**Comment by apu52** [comment]
@shubhagarwal1 Please try to follow the issue templates which are already provided in the repo to raise your issue , otherwise it will be difficult for me/mentors to assign u the issue without much info.
This issue is good just try to raise a new issue on same topic using the issue templates already given 
Sorry to close this issue for now .
