### ISSUE TITLE
Put Zod  validation on Application Forms and Implenting Toaster Notification 

### ISSUE THREAD

**Issue by shubhagarwal1** [apu52/METAVERSE#1348]
Integrating Zod validation into application forms enhances data integrity by enforcing strict schemas for user inputs. Zod allows you to define validation rules such as required fields, string lengths, and pattern matching, ensuring that only valid data is submitted. Additionally, implementing toaster notifications provides immediate feedback to users, enhancing the overall experience. When a form is submitted, users receive concise alerts—such as success messages or error notifications—informing them of the submission status. This combination of validation and feedback creates a more robust, user-friendly application, guiding users through the form-filling process effectively.

**Comment by apu52** [comment]
@shubhagarwal1 Please try to follow the issue templates which are already provided in the repo to raise your issue , otherwise it will be difficult for me/mentors to assign u the issue without much info.
This issue is good just try to raise a new issue on same topic using the issue templates already given 
Sorry to close this issue for now .
