### ISSUE TITLE
ADD FAQ and Feedback page to the application 

### ISSUE THREAD

**Issue by shubhagarwal1** [apu52/METAVERSE#1362]
FAQ Page:

A page addressing common questions about the METAVERSE project, how to contribute, and best practices for new developers.
Feedback and Suggestions:

A page where users can submit feedback on existing projects or suggest new ideas for future projects.

**Comment by apu52** [comment]
@shubhagarwal1 Please try to follow the issue templates which are already provided in the repo to raise your issue , otherwise it will be difficult for me/mentors to assign u the issue without much info.
This issue is good just try to raise a new issue on same topic using the issue templates already given 
Sorry to close this issue for now .
